# Generated by Django 6.0.5 on 2026-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('supervisor', 'Supervisor'), ('administrador', 'Administrador')], default='ciudadano', max_length=30),
        ),
    ]
