# Generated by Django 6.0.7 on 2026-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_perfilusuario_rol_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('moderador', 'Moderador de Contenido'), ('administrador', 'Administrador')], default='ciudadano', max_length=30),
        ),
    ]
