# Generated by Django 6.0.7 on 2026-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(choices=[('BS', 'Basura'), ('BV', 'Baches en Vía Pública'), ('FE', 'Fallos de electricidad'), ('FA', 'Fugas de agua'), ('AP', 'Alumbrado público'), ('SD', 'Semáforo dañado')], max_length=5, unique=True),
        ),
    ]
