# Generated by Django 6.0.7 on 2026-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_categoria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='mostrar_en_galeria',
            field=models.BooleanField(default=True),
        ),
    ]
