# Generated by Django 6.0.7 on 2026-07-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_reporte_mostrar_en_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='reseñas/'),
        ),
        migrations.AddField(
            model_name='resena',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='reseñas/'),
        ),
        migrations.AddField(
            model_name='resena',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseñas', to='reportes.reporte'),
        ),
    ]
