# Generated by Django 6.0.7 on 2026-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_resena_foto1_resena_foto2_resena_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
