# Generated by Django 6.0.7 on 2026-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_perfilusuario_ultimo_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='intentos_reapertura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resena',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='resenas/'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='resenas/'),
        ),
    ]
