# Generated by Django 6.0.7 on 2026-07-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_perfilusuario_bloqueado_hasta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='mostrar_en_galeria',
            field=models.BooleanField(default=False),
        ),
    ]
