# Generated by Django 6.0.7 on 2026-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_alter_reporte_mostrar_en_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_verificacion_creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
