# Generated by Django 6.0.7 on 2026-07-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0011_perfilusuario_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='codigo_verificacion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='codigo_verificacion_creado',
        ),
    ]
