"""
Ajustes y Configuración de Django (Settings) para el proyecto 'sistema_reportes'.
Define las bases de datos (MySQL), middlewares, plantillas, validadores,
idioma y directorios estáticos/media del sistema.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
import os
import dj_database_url
from pathlib import Path

# --- Directorio Base del Proyecto ---
# BASE_DIR apunta a la carpeta raíz del proyecto donde se encuentra 'manage.py'
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Configuraciones de Desarrollo y Seguridad Inicial ---

# CLAVE SECRETA (SECRET_KEY): Utilizada por Django para firmar cookies, sesiones y tokens de seguridad.
# IMPORTANTE: Mantener esta clave secreta en entornos de producción.
SECRET_KEY = 'django-insecure-2i$=-u@@bum65%_*6fp*dioktm+-j3g7lk&6vj89x#5jx9y1n&'

# MODO DE DEPURACIÓN (DEBUG): Si está en True, Django mostrará páginas detalladas de error en el navegador.
# Debe ponerse en False en producción por motivos de seguridad.
DEBUG = False

# HOSTS PERMITIDOS (ALLOWED_HOSTS): Lista de nombres de dominio o IPs bajo los cuales el sitio puede operar.
# El valor '*' permite que responda a cualquier host (útil en desarrollo local).
ALLOWED_HOSTS = ['*']
# --- Configuración de API de Mapbox ---
# Sustituye 'TU_MAPBOX_ACCESS_TOKEN_AQUI' por tu Token de Acceso de Mapbox.
MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoicmVuZTEyIiwiYSI6ImNtcm5zbndmdjNnYzgyd245ZnR0a2V6N3oifQ.ReSA-UNAUWm0HgYx5MuDNg'

# ORÍGENES DE CONFIANZA PARA CSRF (CSRF_TRUSTED_ORIGINS):
# Lista de orígenes de confianza para peticiones seguras (HTTPS).
# Es necesario para evitar el error "Origin checking failed" al acceder mediante túneles locales (localtunnel, ngrok, etc.).
CSRF_TRUSTED_ORIGINS = [
    'https://*.loca.lt',
    'https://*.ngrok-free.app',
    'http://127.0.0.1',
    'http://localhost',
]


# --- Definición de Aplicaciones del Proyecto ---

# INSTALLED_APPS registra todos los módulos/aplicaciones que forman parte del sistema Django.
INSTALLED_APPS = [
    # Aplicaciones nativas de Django:
    'django.contrib.admin',          # Sitio de administración oficial de Django (/admin/).
    'django.contrib.auth',           # Sistema de autenticación de usuarios y permisos.
    'django.contrib.contenttypes',   # Permite asociar tipos de contenido con permisos/modelos.
    'django.contrib.sessions',       # Gestión de sesiones de usuario en el servidor.
    'django.contrib.messages',       # Framework de notificaciones/mensajes temporales (Alertas flash).
    'django.contrib.staticfiles',    # Gestión de archivos estáticos corporativos (CSS, JS, imágenes).
    
    # Aplicaciones locales creadas para este proyecto:
    'reportes',                      # Aplicación principal de registro y gestión de incidentes urbanos.
]


# --- Componentes Intermediarios (Middleware) ---

# MIDDLEWARE procesa cada petición (Request) y respuesta (Response) que entran y salen del servidor.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',             # Implementa cabeceras de seguridad HTTP básicas.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',       # Habilita el almacenamiento de sesiones en las peticiones.
    'django.middleware.common.CommonMiddleware',                 # Gestión de URLs limpias (ej. añadir barra diagonal al final).
    'django.middleware.csrf.CsrfViewMiddleware',                 # Protección contra vulnerabilidades de falsificación de petición en sitios cruzados (CSRF).
    'django.contrib.auth.middleware.AuthenticationMiddleware',   # Asocia el usuario actual a la petición HTTP (request.user).
    'reportes.middleware.ActiveUserMiddleware',                  # Registra la actividad de usuarios en línea.
    'django.contrib.messages.middleware.MessageMiddleware',       # Habilita el manejo de mensajes/alertas de usuario.
    'django.middleware.clickjacking.XFrameOptionsMiddleware',     # Evita que el sitio sea embebido en iFrames de otros dominios (Clickjacking).
]

# Configuración de URL raíz del proyecto
ROOT_URLCONF = 'sistema_reportes.urls'


# --- Motor de Plantillas (Templates) ---

# Define cómo Django localiza y compila los archivos HTML utilizando variables dinámicas.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # Motor de plantillas oficial de Django
        'DIRS': [], # Directorios adicionales donde buscar plantillas fuera de las aplicaciones
        'APP_DIRS': True, # Indica a Django que busque plantillas dentro de la carpeta 'templates' de cada app instalada
        'OPTIONS': {
            'context_processors': [
                # Procesadores de contexto por defecto de Django:
                'django.template.context_processors.request',          # Permite acceder al objeto request en las plantillas HTML
                'django.contrib.auth.context_processors.auth',         # Permite acceder al objeto user (request.user) en plantillas
                'django.contrib.messages.context_processors.messages', # Permite iterar sobre los mensajes flash de éxito o error
                
                # Procesador de contexto personalizado de la app reportes:
                'reportes.context_processors.notificaciones_context',   # Inyecta el contador global de notificaciones no leídas
            ],
        },
    },
]

# Configuración del punto de entrada de la aplicación WSGI para servidores web tradicionales
WSGI_APPLICATION = 'sistema_reportes.wsgi.application'


# --- Bases de Datos (Database) ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# CONFIGURACIÓN ALTERNATIVA PARA SQLITE (Legacy / Respaldos locales):
# #DATABASES = {
# #   'default': {
# #       'ENGINE': 'django.db.backends.sqlite3',
# #        'NAME': BASE_DIR / 'db.sqlite3',
# #   }
# #}



# CONFIGURACIÓN ACTIVA PARA MYSQL
DATABASES = {
    'default': dj_database_url.config(
        default='mysql://root:rene1234@127.0.0.1:3306/sistema_reportes_db',
        conn_max_age=600
    )
}

# --- Validadores de Seguridad para Contraseñas ---
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Evitan que los usuarios utilicen contraseñas débiles o muy comunes al registrarse.
AUTH_PASSWORD_VALIDATORS = [
    {
        # Valida que la contraseña no sea similar a los datos personales del usuario (nombre, correo).
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Valida que la contraseña posea una longitud mínima requerida.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Compara la contraseña con una lista de las contraseñas más comunes y vulnerables a ataques de diccionario.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Verifica que la contraseña no contenga únicamente caracteres numéricos.
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Configuración del Idioma y Zona Horaria (Internacionalización) ---
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Código de idioma de la aplicación (es-mx = Español de México)
LANGUAGE_CODE = 'es-mx'

# Zona horaria del servidor para gestionar la hora de los reportes viales y urbanos
TIME_ZONE = 'America/Mexico_City'

# Habilita el sistema de traducción e internacionalización de Django
USE_I18N = True

# Habilita el uso de la zona horaria definida en TIME_ZONE en la base de datos
USE_TZ = True


# --- Gestión de Archivos Estáticos (CSS, JavaScript, Logos) ---
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# URL pública que se utilizará para referenciar los archivos estáticos en las plantillas HTML (ej: /static/css/inicio.css)
STATIC_URL = '/static/'

# Directorios adicionales de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Carpeta física en el disco duro donde django recolectará todos los archivos estáticos para producción (collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Habilitar WhiteNoise para comprimir y cachear estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Evita errores 500 si algún archivo estático no se encuentra en el manifest
WHITENOISE_MANIFEST_STRICT = False

# --- Gestión de Archivos Multimedia (Imágenes y Evidencias subidas por ciudadanos) ---

# URL pública utilizada para acceder a los archivos subidos por el usuario desde el navegador (ej: /media/reportes/bache.png)
MEDIA_URL = '/media/'

# Carpeta física en el disco duro del servidor donde se guardarán las imágenes de evidencias (ej. media/)
MEDIA_ROOT = BASE_DIR / 'media'


# --- Configuración de Redirección de Inicio de Sesión ---

# URL o vista a la que redirigirá Django si un usuario no autenticado intenta acceder a una sección privada (protegida con @login_required)
LOGIN_URL = 'registro'

# Vista de fallos de verificación CSRF para evitar mostrar la contraseña
CSRF_FAILURE_VIEW = 'reportes.views.custom_csrf_failure'

# --- Configuración del Servidor de Correos (SMTP) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'reportespigrica@gmail.com'
EMAIL_HOST_PASSWORD = 'fcsdlejhcchpkvww'

# --- Configuración de Sesiones e Inactividad ---
# Expira la sesión tras 10 minutos (600 segundos) de inactividad
SESSION_COOKIE_AGE = 600
# Guarda la sesión y actualiza la cookie en cada petición para reiniciar el contador de inactividad
SESSION_SAVE_EVERY_REQUEST = True
# Expira la sesión cuando el usuario cierra el navegador o la pestaña
SESSION_EXPIRE_AT_BROWSER_CLOSE = True